// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: oauth/oauth.proto

package oauth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClientId            string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                    // Client ID
	ResponseType        string                 `protobuf:"bytes,2,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`                        // Response type, e.g., "code"
	RedirectUri         string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`                           // Redirect URI
	Scope               string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`                                                          // Scopes requested
	State               string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                                          // State parameter for CSRF protection
	CodeChallenge       string                 `protobuf:"bytes,6,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`                     // Code challenge for PKCE
	CodeChallengeMethod string                 `protobuf:"bytes,7,opt,name=code_challenge_method,json=codeChallengeMethod,proto3" json:"code_challenge_method,omitempty"` // Method for code challenge, e.g., "S256"
	Version             string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`                                                      // Version of the OAuth protocol, e.g., "2.0"
	Nonce               string                 `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                          // Nonce for additional security, used in OpenID Connect
	Device              string                 `protobuf:"bytes,10,opt,name=device,proto3" json:"device,omitempty"`                                                       // Device information, used for device authorization
	Mode                string                 `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode,omitempty"`                                                           // Country code for the user
	DebugHost           string                 `protobuf:"bytes,12,opt,name=debug_host,json=debugHost,proto3" json:"debug_host,omitempty"`                                // Debug host for testing purposes
	GrantType           string                 `protobuf:"bytes,13,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`                                // Grant type, e.g., "authorization_code"
	Legacy              bool                   `protobuf:"varint,14,opt,name=legacy,proto3" json:"legacy,omitempty"`                                                      // Legacy flag for compatibility with older clients
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_oauth_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizeRequest) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthorizeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizeRequest) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *AuthorizeRequest) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *AuthorizeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AuthorizeRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthorizeRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *AuthorizeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AuthorizeRequest) GetDebugHost() string {
	if x != nil {
		return x.DebugHost
	}
	return ""
}

func (x *AuthorizeRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *AuthorizeRequest) GetLegacy() bool {
	if x != nil {
		return x.Legacy
	}
	return false
}

type AuthorizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                              // Authorization code
	RedirectUri     string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`             // Redirect URI to send the user back to
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                                            // State parameter to match the request
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                          // Status of the authorization request
	UserCode        string                 `protobuf:"bytes,5,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`                      // User code for device authorization
	DeviceCode      string                 `protobuf:"bytes,6,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`                // Device code for device authorization
	ExpiresIn       int32                  `protobuf:"varint,7,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`                  // Expiration time of the authorization code in seconds
	VerificationUri string                 `protobuf:"bytes,8,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"` // Verification URI for device authorization
	Interval        string                 `protobuf:"bytes,10,opt,name=interval,proto3" json:"interval,omitempty"`                                     // Polling interval for device authorization
	ExpiresInTs     int64                  `protobuf:"varint,11,opt,name=expires_in_ts,json=expiresInTs,proto3" json:"expires_in_ts,omitempty"`         // string identity = 4;
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_oauth_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthorizeResponse) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizeResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizeResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *AuthorizeResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *AuthorizeResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AuthorizeResponse) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *AuthorizeResponse) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *AuthorizeResponse) GetExpiresInTs() int64 {
	if x != nil {
		return x.ExpiresInTs
	}
	return 0
}

type DeviceCodeAuthorizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserCode        string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`                      // User code for device authorization
	DeviceCode      string                 `protobuf:"bytes,2,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`                // Device code for device authorization
	ExpiresIn       int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`                  // Expiration time of the authorization code in seconds
	VerificationUri string                 `protobuf:"bytes,4,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"` // Verification URI for device authorization
	Interval        int32                  `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`                                     // Polling interval for device authorization
	ExpiresInTs     int64                  `protobuf:"varint,7,opt,name=expires_in_ts,json=expiresInTs,proto3" json:"expires_in_ts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceCodeAuthorizeResponse) Reset() {
	*x = DeviceCodeAuthorizeResponse{}
	mi := &file_oauth_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeAuthorizeResponse) ProtoMessage() {}

func (x *DeviceCodeAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*DeviceCodeAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceCodeAuthorizeResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceCodeAuthorizeResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *DeviceCodeAuthorizeResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *DeviceCodeAuthorizeResponse) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *DeviceCodeAuthorizeResponse) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *DeviceCodeAuthorizeResponse) GetExpiresInTs() int64 {
	if x != nil {
		return x.ExpiresInTs
	}
	return 0
}

type AuthorizeState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Code                string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State               string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                                // State parameter for CSRF protection
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // Status of the authorization request
	RedirectUri         string                 `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"` // Redirect URI
	Scope               string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	ResponseType        string                 `protobuf:"bytes,6,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	Version             string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	CodeChallenge       string                 `protobuf:"bytes,8,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`                     // Code challenge for PKCE
	CodeChallengeMethod string                 `protobuf:"bytes,9,opt,name=code_challenge_method,json=codeChallengeMethod,proto3" json:"code_challenge_method,omitempty"` // Method for code challenge, e.g., "S256"
	ClientId            string                 `protobuf:"bytes,10,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Device              string                 `protobuf:"bytes,11,opt,name=device,proto3" json:"device,omitempty"` // Device information, used for device authorization
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizeState) Reset() {
	*x = AuthorizeState{}
	mi := &file_oauth_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeState) ProtoMessage() {}

func (x *AuthorizeState) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeState.ProtoReflect.Descriptor instead.
func (*AuthorizeState) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeState) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthorizeState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizeState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizeState) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizeState) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthorizeState) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizeState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AuthorizeState) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

func (x *AuthorizeState) GetCodeChallengeMethod() string {
	if x != nil {
		return x.CodeChallengeMethod
	}
	return ""
}

func (x *AuthorizeState) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizeState) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type DeviceCodeAuthorizeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`       // User code for device authorization
	DeviceCode    string                 `protobuf:"bytes,2,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"` // Device code for device authorization
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`   // Expiration time of the authorization code in seconds
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Login         bool                   `protobuf:"varint,5,opt,name=login,proto3" json:"login,omitempty"`       // Indicates if the user is logged in
	Interval      int32                  `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"` // Polling interval for device authorization
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`      // Status of the device authorization request
	State         string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`        // State parameter to match the request
	IntervalTs    int64                  `protobuf:"varint,9,opt,name=interval_ts,json=intervalTs,proto3" json:"interval_ts,omitempty"`
	ExpiresInTs   int64                  `protobuf:"varint,10,opt,name=expires_in_ts,json=expiresInTs,proto3" json:"expires_in_ts,omitempty"`
	AccessToken   string                 `protobuf:"bytes,11,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // Access token
	RefreshToken  string                 `protobuf:"bytes,12,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeAuthorizeState) Reset() {
	*x = DeviceCodeAuthorizeState{}
	mi := &file_oauth_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeAuthorizeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeAuthorizeState) ProtoMessage() {}

func (x *DeviceCodeAuthorizeState) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeAuthorizeState.ProtoReflect.Descriptor instead.
func (*DeviceCodeAuthorizeState) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceCodeAuthorizeState) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceCodeAuthorizeState) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *DeviceCodeAuthorizeState) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *DeviceCodeAuthorizeState) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DeviceCodeAuthorizeState) GetLogin() bool {
	if x != nil {
		return x.Login
	}
	return false
}

func (x *DeviceCodeAuthorizeState) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *DeviceCodeAuthorizeState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceCodeAuthorizeState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DeviceCodeAuthorizeState) GetIntervalTs() int64 {
	if x != nil {
		return x.IntervalTs
	}
	return 0
}

func (x *DeviceCodeAuthorizeState) GetExpiresInTs() int64 {
	if x != nil {
		return x.ExpiresInTs
	}
	return 0
}

func (x *DeviceCodeAuthorizeState) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeviceCodeAuthorizeState) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                                     // Authorization code received from the authorization endpoint
	RedirectUri   string                 `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`    // Redirect URI used in the authorization request
	GrantType     string                 `protobuf:"bytes,5,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`          // Grant type, e.g., "authorization_code"
	CodeVerifier  string                 `protobuf:"bytes,6,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"` // Code verifier for PKCE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_oauth_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *TokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *TokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *TokenRequest) GetCodeVerifier() string {
	if x != nil {
		return x.CodeVerifier
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // Access token
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh token
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`         // Token expiration time in seconds
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`          // Type of the token, e.g., "Bearer"
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`                                   // Scopes granted
	ExpiresInTs   int64                  `protobuf:"varint,6,opt,name=expires_in_ts,json=expiresInTs,proto3" json:"expires_in_ts,omitempty"` // string identity = 6; // User identity associated with the token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_oauth_oauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TokenResponse) GetExpiresInTs() int64 {
	if x != nil {
		return x.ExpiresInTs
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`             // Client ID
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh token
	GrantType     string                 `protobuf:"bytes,4,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`          // Grant type, e.g., "refresh_token"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_oauth_oauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_oauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_oauth_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

var File_oauth_oauth_proto protoreflect.FileDescriptor

const file_oauth_oauth_proto_rawDesc = "" +
	"\n" +
	"\x11oauth/oauth.proto\x12\x11v6.services.oauth\x1a\x1cgoogle/api/annotations.proto\"\xb0\x03\n" +
	"\x10AuthorizeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rresponse_type\x18\x02 \x01(\tR\fresponseType\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12%\n" +
	"\x0ecode_challenge\x18\x06 \x01(\tR\rcodeChallenge\x122\n" +
	"\x15code_challenge_method\x18\a \x01(\tR\x13codeChallengeMethod\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\t \x01(\tR\x05nonce\x12\x16\n" +
	"\x06device\x18\n" +
	" \x01(\tR\x06device\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"debug_host\x18\f \x01(\tR\tdebugHost\x12\x1d\n" +
	"\n" +
	"grant_type\x18\r \x01(\tR\tgrantType\x12\x16\n" +
	"\x06legacy\x18\x0e \x01(\bR\x06legacy\"\xc0\x02\n" +
	"\x11AuthorizeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tuser_code\x18\x05 \x01(\tR\buserCode\x12\x1f\n" +
	"\vdevice_code\x18\x06 \x01(\tR\n" +
	"deviceCode\x12\x1d\n" +
	"\n" +
	"expires_in\x18\a \x01(\x05R\texpiresIn\x12)\n" +
	"\x10verification_uri\x18\b \x01(\tR\x0fverificationUri\x12\x1a\n" +
	"\binterval\x18\n" +
	" \x01(\tR\binterval\x12\"\n" +
	"\rexpires_in_ts\x18\v \x01(\x03R\vexpiresInTs\"\xe5\x01\n" +
	"\x1bDeviceCodeAuthorizeResponse\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12\x1f\n" +
	"\vdevice_code\x18\x02 \x01(\tR\n" +
	"deviceCode\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12)\n" +
	"\x10verification_uri\x18\x04 \x01(\tR\x0fverificationUri\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x05R\binterval\x12\"\n" +
	"\rexpires_in_ts\x18\a \x01(\x03R\vexpiresInTs\"\xda\x02\n" +
	"\x0eAuthorizeState\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12#\n" +
	"\rresponse_type\x18\x06 \x01(\tR\fresponseType\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12%\n" +
	"\x0ecode_challenge\x18\b \x01(\tR\rcodeChallenge\x122\n" +
	"\x15code_challenge_method\x18\t \x01(\tR\x13codeChallengeMethod\x12\x1b\n" +
	"\tclient_id\x18\n" +
	" \x01(\tR\bclientId\x12\x16\n" +
	"\x06device\x18\v \x01(\tR\x06device\"\xfa\x02\n" +
	"\x18DeviceCodeAuthorizeState\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12\x1f\n" +
	"\vdevice_code\x18\x02 \x01(\tR\n" +
	"deviceCode\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x14\n" +
	"\x05login\x18\x05 \x01(\bR\x05login\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x05R\binterval\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x1f\n" +
	"\vinterval_ts\x18\t \x01(\x03R\n" +
	"intervalTs\x12\"\n" +
	"\rexpires_in_ts\x18\n" +
	" \x01(\x03R\vexpiresInTs\x12!\n" +
	"\faccess_token\x18\v \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\f \x01(\tR\frefreshToken\"\x89\x01\n" +
	"\fTokenRequest\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x05 \x01(\tR\tgrantType\x12#\n" +
	"\rcode_verifier\x18\x06 \x01(\tR\fcodeVerifier\"\xcf\x01\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\"\n" +
	"\rexpires_in_ts\x18\x06 \x01(\x03R\vexpiresInTs\"v\n" +
	"\x13RefreshTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x04 \x01(\tR\tgrantType2\xa2\x06\n" +
	"\x12OauthAuthorization\x12v\n" +
	"\tAuthorize\x12#.v6.services.oauth.AuthorizeRequest\x1a$.v6.services.oauth.AuthorizeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v6/oauth/authorize\x12\x83\x01\n" +
	"\n" +
	"DeviceCode\x12#.v6.services.oauth.AuthorizeRequest\x1a..v6.services.oauth.DeviceCodeAuthorizeResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v6/oauth/device_code\x12\x83\x01\n" +
	"\x11GetAuthorizeState\x12!.v6.services.oauth.AuthorizeState\x1a!.v6.services.oauth.AuthorizeState\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v6/oauth/get_authorize_state\x12\x9a\x01\n" +
	"\x12GetDeviceCodeState\x12+.v6.services.oauth.DeviceCodeAuthorizeState\x1a+.v6.services.oauth.DeviceCodeAuthorizeState\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v6/oauth/get_device_code_state\x12m\n" +
	"\bGetToken\x12\x1f.v6.services.oauth.TokenRequest\x1a .v6.services.oauth.TokenResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v6/oauth/get_token\x12|\n" +
	"\fRefreshToken\x12&.v6.services.oauth.RefreshTokenRequest\x1a .v6.services.oauth.TokenResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v6/oauth/refresh_tokenB4Z2github.com/city404/v6-public-rpc-proto/go/v6/oauthb\x06proto3"

var (
	file_oauth_oauth_proto_rawDescOnce sync.Once
	file_oauth_oauth_proto_rawDescData []byte
)

func file_oauth_oauth_proto_rawDescGZIP() []byte {
	file_oauth_oauth_proto_rawDescOnce.Do(func() {
		file_oauth_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth_oauth_proto_rawDesc), len(file_oauth_oauth_proto_rawDesc)))
	})
	return file_oauth_oauth_proto_rawDescData
}

var file_oauth_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oauth_oauth_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),            // 0: v6.services.oauth.AuthorizeRequest
	(*AuthorizeResponse)(nil),           // 1: v6.services.oauth.AuthorizeResponse
	(*DeviceCodeAuthorizeResponse)(nil), // 2: v6.services.oauth.DeviceCodeAuthorizeResponse
	(*AuthorizeState)(nil),              // 3: v6.services.oauth.AuthorizeState
	(*DeviceCodeAuthorizeState)(nil),    // 4: v6.services.oauth.DeviceCodeAuthorizeState
	(*TokenRequest)(nil),                // 5: v6.services.oauth.TokenRequest
	(*TokenResponse)(nil),               // 6: v6.services.oauth.TokenResponse
	(*RefreshTokenRequest)(nil),         // 7: v6.services.oauth.RefreshTokenRequest
}
var file_oauth_oauth_proto_depIdxs = []int32{
	0, // 0: v6.services.oauth.OauthAuthorization.Authorize:input_type -> v6.services.oauth.AuthorizeRequest
	0, // 1: v6.services.oauth.OauthAuthorization.DeviceCode:input_type -> v6.services.oauth.AuthorizeRequest
	3, // 2: v6.services.oauth.OauthAuthorization.GetAuthorizeState:input_type -> v6.services.oauth.AuthorizeState
	4, // 3: v6.services.oauth.OauthAuthorization.GetDeviceCodeState:input_type -> v6.services.oauth.DeviceCodeAuthorizeState
	5, // 4: v6.services.oauth.OauthAuthorization.GetToken:input_type -> v6.services.oauth.TokenRequest
	7, // 5: v6.services.oauth.OauthAuthorization.RefreshToken:input_type -> v6.services.oauth.RefreshTokenRequest
	1, // 6: v6.services.oauth.OauthAuthorization.Authorize:output_type -> v6.services.oauth.AuthorizeResponse
	2, // 7: v6.services.oauth.OauthAuthorization.DeviceCode:output_type -> v6.services.oauth.DeviceCodeAuthorizeResponse
	3, // 8: v6.services.oauth.OauthAuthorization.GetAuthorizeState:output_type -> v6.services.oauth.AuthorizeState
	4, // 9: v6.services.oauth.OauthAuthorization.GetDeviceCodeState:output_type -> v6.services.oauth.DeviceCodeAuthorizeState
	6, // 10: v6.services.oauth.OauthAuthorization.GetToken:output_type -> v6.services.oauth.TokenResponse
	6, // 11: v6.services.oauth.OauthAuthorization.RefreshToken:output_type -> v6.services.oauth.TokenResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oauth_oauth_proto_init() }
func file_oauth_oauth_proto_init() {
	if File_oauth_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth_oauth_proto_rawDesc), len(file_oauth_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauth_oauth_proto_goTypes,
		DependencyIndexes: file_oauth_oauth_proto_depIdxs,
		MessageInfos:      file_oauth_oauth_proto_msgTypes,
	}.Build()
	File_oauth_oauth_proto = out.File
	file_oauth_oauth_proto_goTypes = nil
	file_oauth_oauth_proto_depIdxs = nil
}
