// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sftp/public_sftp.proto

package sftpconfig

import (
	common "github.com/city404/v6-public-rpc-proto/go/v6/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SftpConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdentity  string                 `protobuf:"bytes,1,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"`
	EnableFlag    int32                  `protobuf:"varint,2,opt,name=enable_flag,json=enableFlag,proto3" json:"enable_flag,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	WriteFlag     int32                  `protobuf:"varint,4,opt,name=write_flag,json=writeFlag,proto3" json:"write_flag,omitempty"`
	LockFlag      int32                  `protobuf:"varint,5,opt,name=lock_flag,json=lockFlag,proto3" json:"lock_flag,omitempty"`
	ChunkedFlag   int32                  `protobuf:"varint,6,opt,name=chunked_flag,json=chunkedFlag,proto3" json:"chunked_flag,omitempty"`
	PathStyle     int32                  `protobuf:"varint,7,opt,name=path_style,json=pathStyle,proto3" json:"path_style,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Prefix        string                 `protobuf:"bytes,9,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Code          int32                  `protobuf:"varint,10,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	Username      string                 `protobuf:"bytes,12,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	UpdateTs      int64                  `protobuf:"varint,14,opt,name=update_ts,json=updateTs,proto3" json:"update_ts,omitempty"`
	SshKey        string                 `protobuf:"bytes,15,opt,name=ssh_key,json=sshKey,proto3" json:"ssh_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SftpConfig) Reset() {
	*x = SftpConfig{}
	mi := &file_sftp_public_sftp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SftpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SftpConfig) ProtoMessage() {}

func (x *SftpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sftp_public_sftp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SftpConfig.ProtoReflect.Descriptor instead.
func (*SftpConfig) Descriptor() ([]byte, []int) {
	return file_sftp_public_sftp_proto_rawDescGZIP(), []int{0}
}

func (x *SftpConfig) GetUserIdentity() string {
	if x != nil {
		return x.UserIdentity
	}
	return ""
}

func (x *SftpConfig) GetEnableFlag() int32 {
	if x != nil {
		return x.EnableFlag
	}
	return 0
}

func (x *SftpConfig) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *SftpConfig) GetWriteFlag() int32 {
	if x != nil {
		return x.WriteFlag
	}
	return 0
}

func (x *SftpConfig) GetLockFlag() int32 {
	if x != nil {
		return x.LockFlag
	}
	return 0
}

func (x *SftpConfig) GetChunkedFlag() int32 {
	if x != nil {
		return x.ChunkedFlag
	}
	return 0
}

func (x *SftpConfig) GetPathStyle() int32 {
	if x != nil {
		return x.PathStyle
	}
	return 0
}

func (x *SftpConfig) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SftpConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SftpConfig) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SftpConfig) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SftpConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SftpConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SftpConfig) GetUpdateTs() int64 {
	if x != nil {
		return x.UpdateTs
	}
	return 0
}

func (x *SftpConfig) GetSshKey() string {
	if x != nil {
		return x.SshKey
	}
	return ""
}

var File_sftp_public_sftp_proto protoreflect.FileDescriptor

const file_sftp_public_sftp_proto_rawDesc = "" +
	"\n" +
	"\x16sftp/public_sftp.proto\x12\x0fv6.services.pub\x1a\x17common/pub_common.proto\"\xb0\x03\n" +
	"\n" +
	"SftpConfig\x12#\n" +
	"\ruser_identity\x18\x01 \x01(\tR\fuserIdentity\x12\x1f\n" +
	"\venable_flag\x18\x02 \x01(\x05R\n" +
	"enableFlag\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x1d\n" +
	"\n" +
	"write_flag\x18\x04 \x01(\x05R\twriteFlag\x12\x1b\n" +
	"\tlock_flag\x18\x05 \x01(\x05R\blockFlag\x12!\n" +
	"\fchunked_flag\x18\x06 \x01(\x05R\vchunkedFlag\x12\x1d\n" +
	"\n" +
	"path_style\x18\a \x01(\x05R\tpathStyle\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x16\n" +
	"\x06prefix\x18\t \x01(\tR\x06prefix\x12\x12\n" +
	"\x04code\x18\n" +
	" \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12\x1a\n" +
	"\busername\x18\f \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x12\x1b\n" +
	"\tupdate_ts\x18\x0e \x01(\x03R\bupdateTs\x12\x17\n" +
	"\assh_key\x18\x0f \x01(\tR\x06sshKey2\xd4\x03\n" +
	"\rPubSftpConfig\x12A\n" +
	"\x03Get\x12\x1b.v6.services.pub.SftpConfig\x1a\x1b.v6.services.pub.SftpConfig\"\x00\x12D\n" +
	"\x06Update\x12\x1b.v6.services.pub.SftpConfig\x1a\x1b.v6.services.pub.SftpConfig\"\x00\x12D\n" +
	"\x06Enable\x12\x1b.v6.services.pub.SftpConfig\x1a\x1b.v6.services.pub.SftpConfig\"\x00\x12E\n" +
	"\aDisable\x12\x1b.v6.services.pub.SftpConfig\x1a\x1b.v6.services.pub.SftpConfig\"\x00\x12H\n" +
	"\n" +
	"UpdateKeys\x12\x1b.v6.services.pub.SftpConfig\x1a\x1b.v6.services.pub.SftpConfig\"\x00\x12c\n" +
	"\x10ValidateUserName\x12\x1b.v6.services.pub.SftpConfig\x1a0.v6.services.pub.common.UserNameValidateResponse\"\x00B9Z7github.com/city404/v6-public-rpc-proto/go/v6/sftpconfigb\x06proto3"

var (
	file_sftp_public_sftp_proto_rawDescOnce sync.Once
	file_sftp_public_sftp_proto_rawDescData []byte
)

func file_sftp_public_sftp_proto_rawDescGZIP() []byte {
	file_sftp_public_sftp_proto_rawDescOnce.Do(func() {
		file_sftp_public_sftp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sftp_public_sftp_proto_rawDesc), len(file_sftp_public_sftp_proto_rawDesc)))
	})
	return file_sftp_public_sftp_proto_rawDescData
}

var file_sftp_public_sftp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sftp_public_sftp_proto_goTypes = []any{
	(*SftpConfig)(nil),                      // 0: v6.services.pub.SftpConfig
	(*common.UserNameValidateResponse)(nil), // 1: v6.services.pub.common.UserNameValidateResponse
}
var file_sftp_public_sftp_proto_depIdxs = []int32{
	0, // 0: v6.services.pub.PubSftpConfig.Get:input_type -> v6.services.pub.SftpConfig
	0, // 1: v6.services.pub.PubSftpConfig.Update:input_type -> v6.services.pub.SftpConfig
	0, // 2: v6.services.pub.PubSftpConfig.Enable:input_type -> v6.services.pub.SftpConfig
	0, // 3: v6.services.pub.PubSftpConfig.Disable:input_type -> v6.services.pub.SftpConfig
	0, // 4: v6.services.pub.PubSftpConfig.UpdateKeys:input_type -> v6.services.pub.SftpConfig
	0, // 5: v6.services.pub.PubSftpConfig.ValidateUserName:input_type -> v6.services.pub.SftpConfig
	0, // 6: v6.services.pub.PubSftpConfig.Get:output_type -> v6.services.pub.SftpConfig
	0, // 7: v6.services.pub.PubSftpConfig.Update:output_type -> v6.services.pub.SftpConfig
	0, // 8: v6.services.pub.PubSftpConfig.Enable:output_type -> v6.services.pub.SftpConfig
	0, // 9: v6.services.pub.PubSftpConfig.Disable:output_type -> v6.services.pub.SftpConfig
	0, // 10: v6.services.pub.PubSftpConfig.UpdateKeys:output_type -> v6.services.pub.SftpConfig
	1, // 11: v6.services.pub.PubSftpConfig.ValidateUserName:output_type -> v6.services.pub.common.UserNameValidateResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sftp_public_sftp_proto_init() }
func file_sftp_public_sftp_proto_init() {
	if File_sftp_public_sftp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sftp_public_sftp_proto_rawDesc), len(file_sftp_public_sftp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sftp_public_sftp_proto_goTypes,
		DependencyIndexes: file_sftp_public_sftp_proto_depIdxs,
		MessageInfos:      file_sftp_public_sftp_proto_msgTypes,
	}.Build()
	File_sftp_public_sftp_proto = out.File
	file_sftp_public_sftp_proto_goTypes = nil
	file_sftp_public_sftp_proto_depIdxs = nil
}
