// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: userfile/public_user_file.proto

package userfile

import (
	common "github.com/city404/v6-public-rpc-proto/go/v6/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identity        string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Parent          string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Path            string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	MimeType        string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size            int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Type            int64                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	CreateTs        int64                  `protobuf:"varint,9,opt,name=create_ts,json=createTs,proto3" json:"create_ts,omitempty"`
	UpdateTs        int64                  `protobuf:"varint,10,opt,name=update_ts,json=updateTs,proto3" json:"update_ts,omitempty"`
	DeleteTs        int64                  `protobuf:"varint,11,opt,name=delete_ts,json=deleteTs,proto3" json:"delete_ts,omitempty"`
	Deleted         bool                   `protobuf:"varint,12,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Dir             bool                   `protobuf:"varint,13,opt,name=dir,proto3" json:"dir,omitempty"`
	Hidden          bool                   `protobuf:"varint,14,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Locked          bool                   `protobuf:"varint,15,opt,name=locked,proto3" json:"locked,omitempty"`
	Shared          bool                   `protobuf:"varint,16,opt,name=shared,proto3" json:"shared,omitempty"`
	Starred         bool                   `protobuf:"varint,17,opt,name=starred,proto3" json:"starred,omitempty"`
	Trashed         bool                   `protobuf:"varint,18,opt,name=trashed,proto3" json:"trashed,omitempty"`
	LockedAt        int64                  `protobuf:"varint,19,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	LockedBy        string                 `protobuf:"bytes,20,opt,name=locked_by,json=lockedBy,proto3" json:"locked_by,omitempty"`
	SharedAt        int64                  `protobuf:"varint,21,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	Flag            int64                  `protobuf:"varint,22,opt,name=flag,proto3" json:"flag,omitempty"`
	Unique          string                 `protobuf:"bytes,23,opt,name=unique,proto3" json:"unique,omitempty"`
	ContentIdentity string                 `protobuf:"bytes,24,opt,name=content_identity,json=contentIdentity,proto3" json:"content_identity,omitempty"`
	Label           int64                  `protobuf:"varint,25,opt,name=label,proto3" json:"label,omitempty"`
	StoreType       int64                  `protobuf:"varint,26,opt,name=store_type,json=storeType,proto3" json:"store_type,omitempty"`
	Version         int64                  `protobuf:"varint,27,opt,name=version,proto3" json:"version,omitempty"`
	Files           int64                  `protobuf:"varint,28,opt,name=files,proto3" json:"files,omitempty"`
	Direcotries     int64                  `protobuf:"varint,29,opt,name=direcotries,proto3" json:"direcotries,omitempty"`
	Nodes           int64                  `protobuf:"varint,30,opt,name=nodes,proto3" json:"nodes,omitempty"`
	SortName        string                 `protobuf:"bytes,31,opt,name=sort_name,json=sortName,proto3" json:"sort_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_userfile_public_user_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *File) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *File) GetCreateTs() int64 {
	if x != nil {
		return x.CreateTs
	}
	return 0
}

func (x *File) GetUpdateTs() int64 {
	if x != nil {
		return x.UpdateTs
	}
	return 0
}

func (x *File) GetDeleteTs() int64 {
	if x != nil {
		return x.DeleteTs
	}
	return 0
}

func (x *File) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *File) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

func (x *File) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *File) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *File) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *File) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *File) GetTrashed() bool {
	if x != nil {
		return x.Trashed
	}
	return false
}

func (x *File) GetLockedAt() int64 {
	if x != nil {
		return x.LockedAt
	}
	return 0
}

func (x *File) GetLockedBy() string {
	if x != nil {
		return x.LockedBy
	}
	return ""
}

func (x *File) GetSharedAt() int64 {
	if x != nil {
		return x.SharedAt
	}
	return 0
}

func (x *File) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *File) GetUnique() string {
	if x != nil {
		return x.Unique
	}
	return ""
}

func (x *File) GetContentIdentity() string {
	if x != nil {
		return x.ContentIdentity
	}
	return ""
}

func (x *File) GetLabel() int64 {
	if x != nil {
		return x.Label
	}
	return 0
}

func (x *File) GetStoreType() int64 {
	if x != nil {
		return x.StoreType
	}
	return 0
}

func (x *File) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *File) GetFiles() int64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *File) GetDirecotries() int64 {
	if x != nil {
		return x.Direcotries
	}
	return 0
}

func (x *File) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *File) GetSortName() string {
	if x != nil {
		return x.SortName
	}
	return ""
}

type FileListRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Parent        *File                   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Filter        *File                   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	ListInfo      *common.ScanListRequest `protobuf:"bytes,3,opt,name=list_info,json=listInfo,proto3" json:"list_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileListRequest) GetParent() *File {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *FileListRequest) GetFilter() *File {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FileListRequest) GetListInfo() *common.ScanListRequest {
	if x != nil {
		return x.ListInfo
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ListInfo      *common.ScanListRequest `protobuf:"bytes,3,opt,name=list_info,json=listInfo,proto3" json:"list_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchRequest) GetListInfo() *common.ScanListRequest {
	if x != nil {
		return x.ListInfo
	}
	return nil
}

type FileListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Files         []*File                 `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	ListInfo      *common.ScanListRequest `protobuf:"bytes,2,opt,name=list_info,json=listInfo,proto3" json:"list_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{3}
}

func (x *FileListResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileListResponse) GetListInfo() *common.ScanListRequest {
	if x != nil {
		return x.ListInfo
	}
	return nil
}

type BatchOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        []*File                `protobuf:"bytes,1,rep,name=source,proto3" json:"source,omitempty"`
	Dest          *File                  `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Operation     int32                  `protobuf:"varint,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Flag          int32                  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperationRequest) Reset() {
	*x = BatchOperationRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperationRequest) ProtoMessage() {}

func (x *BatchOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperationRequest.ProtoReflect.Descriptor instead.
func (*BatchOperationRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{4}
}

func (x *BatchOperationRequest) GetSource() []*File {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *BatchOperationRequest) GetDest() *File {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *BatchOperationRequest) GetOperation() int32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *BatchOperationRequest) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type BatchOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Affected      int64                  `protobuf:"varint,3,opt,name=affected,proto3" json:"affected,omitempty"`
	CreateTs      int64                  `protobuf:"varint,4,opt,name=create_ts,json=createTs,proto3" json:"create_ts,omitempty"`
	Progress      int64                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperationResponse) Reset() {
	*x = BatchOperationResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperationResponse) ProtoMessage() {}

func (x *BatchOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperationResponse.ProtoReflect.Descriptor instead.
func (*BatchOperationResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{5}
}

func (x *BatchOperationResponse) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *BatchOperationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BatchOperationResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

func (x *BatchOperationResponse) GetCreateTs() int64 {
	if x != nil {
		return x.CreateTs
	}
	return 0
}

func (x *BatchOperationResponse) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type ManageRTCRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string content_identity = 1;
	Sdp            string `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Offer          string `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	ClientIdentity string `protobuf:"bytes,3,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManageRTCRequest) Reset() {
	*x = ManageRTCRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageRTCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageRTCRequest) ProtoMessage() {}

func (x *ManageRTCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageRTCRequest.ProtoReflect.Descriptor instead.
func (*ManageRTCRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{6}
}

func (x *ManageRTCRequest) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *ManageRTCRequest) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *ManageRTCRequest) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

type ManageRTCResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string content_identity = 1;
	FileSize      int64  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	EncodeKey     string `protobuf:"bytes,2,opt,name=encode_key,json=encodeKey,proto3" json:"encode_key,omitempty"`
	Sdp           string `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Connection    string `protobuf:"bytes,5,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageRTCResponse) Reset() {
	*x = ManageRTCResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageRTCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageRTCResponse) ProtoMessage() {}

func (x *ManageRTCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageRTCResponse.ProtoReflect.Descriptor instead.
func (*ManageRTCResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{7}
}

func (x *ManageRTCResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ManageRTCResponse) GetEncodeKey() string {
	if x != nil {
		return x.EncodeKey
	}
	return ""
}

func (x *ManageRTCResponse) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *ManageRTCResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManageRTCResponse) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type SendIceCandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string content_identity = 1;
	ClientIdentity string `protobuf:"bytes,1,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	Candidate      string `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendIceCandidateRequest) Reset() {
	*x = SendIceCandidateRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendIceCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIceCandidateRequest) ProtoMessage() {}

func (x *SendIceCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIceCandidateRequest.ProtoReflect.Descriptor instead.
func (*SendIceCandidateRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{8}
}

func (x *SendIceCandidateRequest) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

func (x *SendIceCandidateRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type SendIceCandidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string content_identity = 1;
	ClientIdentity string `protobuf:"bytes,1,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	Candidate      string `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendIceCandidateResponse) Reset() {
	*x = SendIceCandidateResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendIceCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIceCandidateResponse) ProtoMessage() {}

func (x *SendIceCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIceCandidateResponse.ProtoReflect.Descriptor instead.
func (*SendIceCandidateResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{9}
}

func (x *SendIceCandidateResponse) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

func (x *SendIceCandidateResponse) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type GetIceCandidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string content_identity = 1;
	ClientIdentity string `protobuf:"bytes,1,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	Candidate      string `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIceCandidateRequest) Reset() {
	*x = GetIceCandidateRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIceCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIceCandidateRequest) ProtoMessage() {}

func (x *GetIceCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIceCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetIceCandidateRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{10}
}

func (x *GetIceCandidateRequest) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

func (x *GetIceCandidateRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type GetIceCandidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string content_identity = 1;
	ClientIdentity string   `protobuf:"bytes,1,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	Candidate      []string `protobuf:"bytes,2,rep,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIceCandidateResponse) Reset() {
	*x = GetIceCandidateResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIceCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIceCandidateResponse) ProtoMessage() {}

func (x *GetIceCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIceCandidateResponse.ProtoReflect.Descriptor instead.
func (*GetIceCandidateResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{11}
}

func (x *GetIceCandidateResponse) GetClientIdentity() string {
	if x != nil {
		return x.ClientIdentity
	}
	return ""
}

func (x *GetIceCandidateResponse) GetCandidate() []string {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type ParseFileSliceResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContentIdentity      string                 `protobuf:"bytes,1,opt,name=content_identity,json=contentIdentity,proto3" json:"content_identity,omitempty"`
	MetaNodes            []string               `protobuf:"bytes,2,rep,name=meta_nodes,json=metaNodes,proto3" json:"meta_nodes,omitempty"`
	RawNodes             []string               `protobuf:"bytes,3,rep,name=raw_nodes,json=rawNodes,proto3" json:"raw_nodes,omitempty"`
	FileSize             int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Sizes                []*SliceSize           `protobuf:"bytes,5,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Sha1                 string                 `protobuf:"bytes,6,opt,name=sha1,proto3" json:"sha1,omitempty"`
	WcsEtag              string                 `protobuf:"bytes,7,opt,name=wcs_etag,json=wcsEtag,proto3" json:"wcs_etag,omitempty"`
	Name                 string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	StoreType            int64                  `protobuf:"varint,10,opt,name=store_type,json=storeType,proto3" json:"store_type,omitempty"`
	RawDownloadAddresses []*SliceDownloadInfo   `protobuf:"bytes,11,rep,name=raw_download_addresses,json=rawDownloadAddresses,proto3" json:"raw_download_addresses,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParseFileSliceResponse) Reset() {
	*x = ParseFileSliceResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseFileSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFileSliceResponse) ProtoMessage() {}

func (x *ParseFileSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFileSliceResponse.ProtoReflect.Descriptor instead.
func (*ParseFileSliceResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{12}
}

func (x *ParseFileSliceResponse) GetContentIdentity() string {
	if x != nil {
		return x.ContentIdentity
	}
	return ""
}

func (x *ParseFileSliceResponse) GetMetaNodes() []string {
	if x != nil {
		return x.MetaNodes
	}
	return nil
}

func (x *ParseFileSliceResponse) GetRawNodes() []string {
	if x != nil {
		return x.RawNodes
	}
	return nil
}

func (x *ParseFileSliceResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ParseFileSliceResponse) GetSizes() []*SliceSize {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *ParseFileSliceResponse) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *ParseFileSliceResponse) GetWcsEtag() string {
	if x != nil {
		return x.WcsEtag
	}
	return ""
}

func (x *ParseFileSliceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParseFileSliceResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ParseFileSliceResponse) GetStoreType() int64 {
	if x != nil {
		return x.StoreType
	}
	return 0
}

func (x *ParseFileSliceResponse) GetRawDownloadAddresses() []*SliceDownloadInfo {
	if x != nil {
		return x.RawDownloadAddresses
	}
	return nil
}

type SliceSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartIndex    int64                  `protobuf:"varint,1,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	EndIndex      int64                  `protobuf:"varint,2,opt,name=end_index,json=endIndex,proto3" json:"end_index,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceSize) Reset() {
	*x = SliceSize{}
	mi := &file_userfile_public_user_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceSize) ProtoMessage() {}

func (x *SliceSize) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceSize.ProtoReflect.Descriptor instead.
func (*SliceSize) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{13}
}

func (x *SliceSize) GetStartIndex() int64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *SliceSize) GetEndIndex() int64 {
	if x != nil {
		return x.EndIndex
	}
	return 0
}

func (x *SliceSize) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SliceDownloadAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      []string               `protobuf:"bytes,1,rep,name=identity,proto3" json:"identity,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Flag          int64                  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	Parse         bool                   `protobuf:"varint,5,opt,name=parse,proto3" json:"parse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceDownloadAddressRequest) Reset() {
	*x = SliceDownloadAddressRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceDownloadAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceDownloadAddressRequest) ProtoMessage() {}

func (x *SliceDownloadAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceDownloadAddressRequest.ProtoReflect.Descriptor instead.
func (*SliceDownloadAddressRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{14}
}

func (x *SliceDownloadAddressRequest) GetIdentity() []string {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SliceDownloadAddressRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SliceDownloadAddressRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SliceDownloadAddressRequest) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *SliceDownloadAddressRequest) GetParse() bool {
	if x != nil {
		return x.Parse
	}
	return false
}

type SliceDownloadAddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Addresses      []*SliceDownloadInfo   `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ExpireAt       int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	RequestAddress string                 `protobuf:"bytes,3,opt,name=request_address,json=requestAddress,proto3" json:"request_address,omitempty"`
	Version        int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SliceDownloadAddressResponse) Reset() {
	*x = SliceDownloadAddressResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceDownloadAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceDownloadAddressResponse) ProtoMessage() {}

func (x *SliceDownloadAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceDownloadAddressResponse.ProtoReflect.Descriptor instead.
func (*SliceDownloadAddressResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{15}
}

func (x *SliceDownloadAddressResponse) GetAddresses() []*SliceDownloadInfo {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *SliceDownloadAddressResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *SliceDownloadAddressResponse) GetRequestAddress() string {
	if x != nil {
		return x.RequestAddress
	}
	return ""
}

func (x *SliceDownloadAddressResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type FileDownloadAddressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DownloadAddress string                 `protobuf:"bytes,1,opt,name=download_address,json=downloadAddress,proto3" json:"download_address,omitempty"`
	ExpireAt        int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	RequestAddress  string                 `protobuf:"bytes,3,opt,name=request_address,json=requestAddress,proto3" json:"request_address,omitempty"`
	Version         int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Encrypt         int32                  `protobuf:"varint,5,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	StoreType       int64                  `protobuf:"varint,6,opt,name=store_type,json=storeType,proto3" json:"store_type,omitempty"`
	FileSize        int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Path            string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Name            string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	ContentIdentity string                 `protobuf:"bytes,10,opt,name=content_identity,json=contentIdentity,proto3" json:"content_identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileDownloadAddressResponse) Reset() {
	*x = FileDownloadAddressResponse{}
	mi := &file_userfile_public_user_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadAddressResponse) ProtoMessage() {}

func (x *FileDownloadAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadAddressResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadAddressResponse) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{16}
}

func (x *FileDownloadAddressResponse) GetDownloadAddress() string {
	if x != nil {
		return x.DownloadAddress
	}
	return ""
}

func (x *FileDownloadAddressResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *FileDownloadAddressResponse) GetRequestAddress() string {
	if x != nil {
		return x.RequestAddress
	}
	return ""
}

func (x *FileDownloadAddressResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FileDownloadAddressResponse) GetEncrypt() int32 {
	if x != nil {
		return x.Encrypt
	}
	return 0
}

func (x *FileDownloadAddressResponse) GetStoreType() int64 {
	if x != nil {
		return x.StoreType
	}
	return 0
}

func (x *FileDownloadAddressResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileDownloadAddressResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDownloadAddressResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileDownloadAddressResponse) GetContentIdentity() string {
	if x != nil {
		return x.ContentIdentity
	}
	return ""
}

type SliceDownloadInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identity        string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	DownloadAddress string                 `protobuf:"bytes,2,opt,name=download_address,json=downloadAddress,proto3" json:"download_address,omitempty"`
	DownloadToken   string                 `protobuf:"bytes,3,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	Encrypt         int32                  `protobuf:"varint,4,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	StoreType       int64                  `protobuf:"varint,5,opt,name=store_type,json=storeType,proto3" json:"store_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SliceDownloadInfo) Reset() {
	*x = SliceDownloadInfo{}
	mi := &file_userfile_public_user_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceDownloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceDownloadInfo) ProtoMessage() {}

func (x *SliceDownloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceDownloadInfo.ProtoReflect.Descriptor instead.
func (*SliceDownloadInfo) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{17}
}

func (x *SliceDownloadInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *SliceDownloadInfo) GetDownloadAddress() string {
	if x != nil {
		return x.DownloadAddress
	}
	return ""
}

func (x *SliceDownloadInfo) GetDownloadToken() string {
	if x != nil {
		return x.DownloadToken
	}
	return ""
}

func (x *SliceDownloadInfo) GetEncrypt() int32 {
	if x != nil {
		return x.Encrypt
	}
	return 0
}

func (x *SliceDownloadInfo) GetStoreType() int64 {
	if x != nil {
		return x.StoreType
	}
	return 0
}

type DocFilePreview struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identity       string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Parent         string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Path           string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	MimeType       string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size           int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Type           int64                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	CanPreview     bool                   `protobuf:"varint,9,opt,name=can_preview,json=canPreview,proto3" json:"can_preview,omitempty"`
	PreviewAddress string                 `protobuf:"bytes,10,opt,name=preview_address,json=previewAddress,proto3" json:"preview_address,omitempty"`
	PreviewToken   string                 `protobuf:"bytes,11,opt,name=preview_token,json=previewToken,proto3" json:"preview_token,omitempty"`
	CanEdit        bool                   `protobuf:"varint,12,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	EditAddress    string                 `protobuf:"bytes,13,opt,name=edit_address,json=editAddress,proto3" json:"edit_address,omitempty"`
	EditToken      string                 `protobuf:"bytes,14,opt,name=edit_token,json=editToken,proto3" json:"edit_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocFilePreview) Reset() {
	*x = DocFilePreview{}
	mi := &file_userfile_public_user_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocFilePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocFilePreview) ProtoMessage() {}

func (x *DocFilePreview) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocFilePreview.ProtoReflect.Descriptor instead.
func (*DocFilePreview) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{18}
}

func (x *DocFilePreview) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DocFilePreview) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DocFilePreview) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocFilePreview) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DocFilePreview) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DocFilePreview) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DocFilePreview) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DocFilePreview) GetCanPreview() bool {
	if x != nil {
		return x.CanPreview
	}
	return false
}

func (x *DocFilePreview) GetPreviewAddress() string {
	if x != nil {
		return x.PreviewAddress
	}
	return ""
}

func (x *DocFilePreview) GetPreviewToken() string {
	if x != nil {
		return x.PreviewToken
	}
	return ""
}

func (x *DocFilePreview) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *DocFilePreview) GetEditAddress() string {
	if x != nil {
		return x.EditAddress
	}
	return ""
}

func (x *DocFilePreview) GetEditToken() string {
	if x != nil {
		return x.EditToken
	}
	return ""
}

type DownloadAndPreviewInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Identity              string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Parent                string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                  string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Path                  string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	MimeType              string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size                  int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Type                  int64                  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	CanPreview            bool                   `protobuf:"varint,9,opt,name=can_preview,json=canPreview,proto3" json:"can_preview,omitempty"`
	CanEdit               bool                   `protobuf:"varint,10,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	PreviewType           int32                  `protobuf:"varint,11,opt,name=preview_type,json=previewType,proto3" json:"preview_type,omitempty"`
	DownloadType          int32                  `protobuf:"varint,12,opt,name=download_type,json=downloadType,proto3" json:"download_type,omitempty"`
	Sha1                  string                 `protobuf:"bytes,13,opt,name=sha1,proto3" json:"sha1,omitempty"`
	CanDownload           bool                   `protobuf:"varint,14,opt,name=can_download,json=canDownload,proto3" json:"can_download,omitempty"`
	CannotDownloadMessage string                 `protobuf:"bytes,15,opt,name=cannot_download_message,json=cannotDownloadMessage,proto3" json:"cannot_download_message,omitempty"`
	ContentIdentity       string                 `protobuf:"bytes,16,opt,name=content_identity,json=contentIdentity,proto3" json:"content_identity,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DownloadAndPreviewInfo) Reset() {
	*x = DownloadAndPreviewInfo{}
	mi := &file_userfile_public_user_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadAndPreviewInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAndPreviewInfo) ProtoMessage() {}

func (x *DownloadAndPreviewInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAndPreviewInfo.ProtoReflect.Descriptor instead.
func (*DownloadAndPreviewInfo) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadAndPreviewInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DownloadAndPreviewInfo) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DownloadAndPreviewInfo) GetCanPreview() bool {
	if x != nil {
		return x.CanPreview
	}
	return false
}

func (x *DownloadAndPreviewInfo) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *DownloadAndPreviewInfo) GetPreviewType() int32 {
	if x != nil {
		return x.PreviewType
	}
	return 0
}

func (x *DownloadAndPreviewInfo) GetDownloadType() int32 {
	if x != nil {
		return x.DownloadType
	}
	return 0
}

func (x *DownloadAndPreviewInfo) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetCanDownload() bool {
	if x != nil {
		return x.CanDownload
	}
	return false
}

func (x *DownloadAndPreviewInfo) GetCannotDownloadMessage() string {
	if x != nil {
		return x.CannotDownloadMessage
	}
	return ""
}

func (x *DownloadAndPreviewInfo) GetContentIdentity() string {
	if x != nil {
		return x.ContentIdentity
	}
	return ""
}

type UploadToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccessKey     string                 `protobuf:"bytes,10,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,11,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Bucket        string                 `protobuf:"bytes,12,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Region        string                 `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint      string                 `protobuf:"bytes,14,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Key           string                 `protobuf:"bytes,15,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadToken) Reset() {
	*x = UploadToken{}
	mi := &file_userfile_public_user_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadToken) ProtoMessage() {}

func (x *UploadToken) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadToken.ProtoReflect.Descriptor instead.
func (*UploadToken) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{20}
}

func (x *UploadToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UploadToken) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *UploadToken) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *UploadToken) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadToken) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UploadToken) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *UploadToken) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UploadTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	UploadAddress string                 `protobuf:"bytes,2,opt,name=upload_address,json=uploadAddress,proto3" json:"upload_address,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	UploadToken   string                 `protobuf:"bytes,4,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	UploadKey     string                 `protobuf:"bytes,5,opt,name=upload_key,json=uploadKey,proto3" json:"upload_key,omitempty"`
	AccessKey     string                 `protobuf:"bytes,10,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,11,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Bucket        string                 `protobuf:"bytes,12,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Region        string                 `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint      string                 `protobuf:"bytes,14,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Key           string                 `protobuf:"bytes,15,opt,name=key,proto3" json:"key,omitempty"`
	BlockSize     int64                  `protobuf:"varint,16,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	BlockHashType int64                  `protobuf:"varint,17,opt,name=block_hash_type,json=blockHashType,proto3" json:"block_hash_type,omitempty"`
	BlockVersion  int32                  `protobuf:"varint,18,opt,name=block_version,json=blockVersion,proto3" json:"block_version,omitempty"`
	BlockCodec    int64                  `protobuf:"varint,19,opt,name=block_codec,json=blockCodec,proto3" json:"block_codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTask) Reset() {
	*x = UploadTask{}
	mi := &file_userfile_public_user_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTask) ProtoMessage() {}

func (x *UploadTask) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTask.ProtoReflect.Descriptor instead.
func (*UploadTask) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{21}
}

func (x *UploadTask) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *UploadTask) GetUploadAddress() string {
	if x != nil {
		return x.UploadAddress
	}
	return ""
}

func (x *UploadTask) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *UploadTask) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

func (x *UploadTask) GetUploadKey() string {
	if x != nil {
		return x.UploadKey
	}
	return ""
}

func (x *UploadTask) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *UploadTask) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *UploadTask) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadTask) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UploadTask) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *UploadTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadTask) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *UploadTask) GetBlockHashType() int64 {
	if x != nil {
		return x.BlockHashType
	}
	return 0
}

func (x *UploadTask) GetBlockVersion() int32 {
	if x != nil {
		return x.BlockVersion
	}
	return 0
}

func (x *UploadTask) GetBlockCodec() int64 {
	if x != nil {
		return x.BlockCodec
	}
	return 0
}

type DirectDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Flag          int64                  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientUa      string                 `protobuf:"bytes,6,opt,name=client_ua,json=clientUa,proto3" json:"client_ua,omitempty"`
	VideoCodecs   []string               `protobuf:"bytes,7,rep,name=video_codecs,json=videoCodecs,proto3" json:"video_codecs,omitempty"`
	AudioCodecs   []string               `protobuf:"bytes,8,rep,name=audio_codecs,json=audioCodecs,proto3" json:"audio_codecs,omitempty"`
	Expire        int64                  `protobuf:"varint,9,opt,name=expire,proto3" json:"expire,omitempty"`
	Encrypt       int32                  `protobuf:"varint,10,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Addon         string                 `protobuf:"bytes,11,opt,name=addon,proto3" json:"addon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectDownloadRequest) Reset() {
	*x = DirectDownloadRequest{}
	mi := &file_userfile_public_user_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectDownloadRequest) ProtoMessage() {}

func (x *DirectDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectDownloadRequest.ProtoReflect.Descriptor instead.
func (*DirectDownloadRequest) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{22}
}

func (x *DirectDownloadRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DirectDownloadRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DirectDownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectDownloadRequest) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *DirectDownloadRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DirectDownloadRequest) GetClientUa() string {
	if x != nil {
		return x.ClientUa
	}
	return ""
}

func (x *DirectDownloadRequest) GetVideoCodecs() []string {
	if x != nil {
		return x.VideoCodecs
	}
	return nil
}

func (x *DirectDownloadRequest) GetAudioCodecs() []string {
	if x != nil {
		return x.AudioCodecs
	}
	return nil
}

func (x *DirectDownloadRequest) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *DirectDownloadRequest) GetEncrypt() int32 {
	if x != nil {
		return x.Encrypt
	}
	return 0
}

func (x *DirectDownloadRequest) GetAddon() string {
	if x != nil {
		return x.Addon
	}
	return ""
}

type PreviewStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identity        string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // file identity
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // status code, 0: success, other: fail
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`   // status message
	Path            string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`         // file path
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`     // processing error, playing, paused, loading, ended
	Type            int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`        // file type, 1: video, 2: audio, 3: doc, 4: image
	Num             int32                  `protobuf:"varint,7,opt,name=num,proto3" json:"num,omitempty"`
	ReportTs        int64                  `protobuf:"varint,8,opt,name=report_ts,json=reportTs,proto3" json:"report_ts,omitempty"`                      // report timestamp, unix timestamp in milliseconds
	VideoCodec      string                 `protobuf:"bytes,9,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`                 // video codec
	AudioCodec      string                 `protobuf:"bytes,10,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`                // audio codec
	Width           int32                  `protobuf:"varint,11,opt,name=width,proto3" json:"width,omitempty"`                                           // video width
	Height          int32                  `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`                                         // video height
	Duration        float32                `protobuf:"fixed32,13,opt,name=duration,proto3" json:"duration,omitempty"`                                    // video duration
	Size            int64                  `protobuf:"varint,14,opt,name=size,proto3" json:"size,omitempty"`                                             // file size
	Extra           string                 `protobuf:"bytes,15,opt,name=extra,proto3" json:"extra,omitempty"`                                            // extra info
	UserAgent       string                 `protobuf:"bytes,16,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                   // user agent
	ClientId        string                 `protobuf:"bytes,17,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                      // client id
	ContentIdentity string                 `protobuf:"bytes,18,opt,name=content_identity,json=contentIdentity,proto3" json:"content_identity,omitempty"` // content identity
	ExtraCode       string                 `protobuf:"bytes,19,opt,name=extra_code,json=extraCode,proto3" json:"extra_code,omitempty"`                   // extra code
	ExtraMessage    string                 `protobuf:"bytes,20,opt,name=extra_message,json=extraMessage,proto3" json:"extra_message,omitempty"`          // extra message
	Name            string                 `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`                                              // file name
	PlaybackType    int32                  `protobuf:"varint,22,opt,name=playback_type,json=playbackType,proto3" json:"playback_type,omitempty"`         // playback type, 0: unknown, 1: xg_player, 2: ve_player, 3: dash
	PlayMode        int32                  `protobuf:"varint,23,opt,name=play_mode,json=playMode,proto3" json:"play_mode,omitempty"`                     // play mode: 0: unknown, 1: converted hls, 2: slice file
	CurrentPos      float32                `protobuf:"fixed32,24,opt,name=current_pos,json=currentPos,proto3" json:"current_pos,omitempty"`              // current position
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreviewStatus) Reset() {
	*x = PreviewStatus{}
	mi := &file_userfile_public_user_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewStatus) ProtoMessage() {}

func (x *PreviewStatus) ProtoReflect() protoreflect.Message {
	mi := &file_userfile_public_user_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewStatus.ProtoReflect.Descriptor instead.
func (*PreviewStatus) Descriptor() ([]byte, []int) {
	return file_userfile_public_user_file_proto_rawDescGZIP(), []int{23}
}

func (x *PreviewStatus) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *PreviewStatus) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PreviewStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PreviewStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PreviewStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PreviewStatus) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PreviewStatus) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *PreviewStatus) GetReportTs() int64 {
	if x != nil {
		return x.ReportTs
	}
	return 0
}

func (x *PreviewStatus) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *PreviewStatus) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *PreviewStatus) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PreviewStatus) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PreviewStatus) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PreviewStatus) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PreviewStatus) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *PreviewStatus) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PreviewStatus) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PreviewStatus) GetContentIdentity() string {
	if x != nil {
		return x.ContentIdentity
	}
	return ""
}

func (x *PreviewStatus) GetExtraCode() string {
	if x != nil {
		return x.ExtraCode
	}
	return ""
}

func (x *PreviewStatus) GetExtraMessage() string {
	if x != nil {
		return x.ExtraMessage
	}
	return ""
}

func (x *PreviewStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreviewStatus) GetPlaybackType() int32 {
	if x != nil {
		return x.PlaybackType
	}
	return 0
}

func (x *PreviewStatus) GetPlayMode() int32 {
	if x != nil {
		return x.PlayMode
	}
	return 0
}

func (x *PreviewStatus) GetCurrentPos() float32 {
	if x != nil {
		return x.CurrentPos
	}
	return 0
}

var File_userfile_public_user_file_proto protoreflect.FileDescriptor

const file_userfile_public_user_file_proto_rawDesc = "" +
	"\n" +
	"\x1fuserfile/public_user_file.proto\x12\x0fv6.services.pub\x1a\x17common/pub_common.proto\x1a\x1cgoogle/api/annotations.proto\"\x8e\x06\n" +
	"\x04File\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\b \x01(\x03R\x04type\x12\x1b\n" +
	"\tcreate_ts\x18\t \x01(\x03R\bcreateTs\x12\x1b\n" +
	"\tupdate_ts\x18\n" +
	" \x01(\x03R\bupdateTs\x12\x1b\n" +
	"\tdelete_ts\x18\v \x01(\x03R\bdeleteTs\x12\x18\n" +
	"\adeleted\x18\f \x01(\bR\adeleted\x12\x10\n" +
	"\x03dir\x18\r \x01(\bR\x03dir\x12\x16\n" +
	"\x06hidden\x18\x0e \x01(\bR\x06hidden\x12\x16\n" +
	"\x06locked\x18\x0f \x01(\bR\x06locked\x12\x16\n" +
	"\x06shared\x18\x10 \x01(\bR\x06shared\x12\x18\n" +
	"\astarred\x18\x11 \x01(\bR\astarred\x12\x18\n" +
	"\atrashed\x18\x12 \x01(\bR\atrashed\x12\x1b\n" +
	"\tlocked_at\x18\x13 \x01(\x03R\blockedAt\x12\x1b\n" +
	"\tlocked_by\x18\x14 \x01(\tR\blockedBy\x12\x1b\n" +
	"\tshared_at\x18\x15 \x01(\x03R\bsharedAt\x12\x12\n" +
	"\x04flag\x18\x16 \x01(\x03R\x04flag\x12\x16\n" +
	"\x06unique\x18\x17 \x01(\tR\x06unique\x12)\n" +
	"\x10content_identity\x18\x18 \x01(\tR\x0fcontentIdentity\x12\x14\n" +
	"\x05label\x18\x19 \x01(\x03R\x05label\x12\x1d\n" +
	"\n" +
	"store_type\x18\x1a \x01(\x03R\tstoreType\x12\x18\n" +
	"\aversion\x18\x1b \x01(\x03R\aversion\x12\x14\n" +
	"\x05files\x18\x1c \x01(\x03R\x05files\x12 \n" +
	"\vdirecotries\x18\x1d \x01(\x03R\vdirecotries\x12\x14\n" +
	"\x05nodes\x18\x1e \x01(\x03R\x05nodes\x12\x1b\n" +
	"\tsort_name\x18\x1f \x01(\tR\bsortName\"\xb5\x01\n" +
	"\x0fFileListRequest\x12-\n" +
	"\x06parent\x18\x01 \x01(\v2\x15.v6.services.pub.FileR\x06parent\x12-\n" +
	"\x06filter\x18\x02 \x01(\v2\x15.v6.services.pub.FileR\x06filter\x12D\n" +
	"\tlist_info\x18\x03 \x01(\v2'.v6.services.pub.common.ScanListRequestR\blistInfo\"i\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\tlist_info\x18\x03 \x01(\v2'.v6.services.pub.common.ScanListRequestR\blistInfo\"\x85\x01\n" +
	"\x10FileListResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.v6.services.pub.FileR\x05files\x12D\n" +
	"\tlist_info\x18\x02 \x01(\v2'.v6.services.pub.common.ScanListRequestR\blistInfo\"\xa3\x01\n" +
	"\x15BatchOperationRequest\x12-\n" +
	"\x06source\x18\x01 \x03(\v2\x15.v6.services.pub.FileR\x06source\x12)\n" +
	"\x04dest\x18\x02 \x01(\v2\x15.v6.services.pub.FileR\x04dest\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\x05R\toperation\x12\x12\n" +
	"\x04flag\x18\x04 \x01(\x05R\x04flag\"\x99\x01\n" +
	"\x16BatchOperationResponse\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1a\n" +
	"\baffected\x18\x03 \x01(\x03R\baffected\x12\x1b\n" +
	"\tcreate_ts\x18\x04 \x01(\x03R\bcreateTs\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x03R\bprogress\"c\n" +
	"\x10ManageRTCRequest\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12\x14\n" +
	"\x05offer\x18\x02 \x01(\tR\x05offer\x12'\n" +
	"\x0fclient_identity\x18\x03 \x01(\tR\x0eclientIdentity\"\x95\x01\n" +
	"\x11ManageRTCResponse\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x12\x1d\n" +
	"\n" +
	"encode_key\x18\x02 \x01(\tR\tencodeKey\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"connection\x18\x05 \x01(\tR\n" +
	"connection\"`\n" +
	"\x17SendIceCandidateRequest\x12'\n" +
	"\x0fclient_identity\x18\x01 \x01(\tR\x0eclientIdentity\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\"a\n" +
	"\x18SendIceCandidateResponse\x12'\n" +
	"\x0fclient_identity\x18\x01 \x01(\tR\x0eclientIdentity\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\"_\n" +
	"\x16GetIceCandidateRequest\x12'\n" +
	"\x0fclient_identity\x18\x01 \x01(\tR\x0eclientIdentity\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\"`\n" +
	"\x17GetIceCandidateResponse\x12'\n" +
	"\x0fclient_identity\x18\x01 \x01(\tR\x0eclientIdentity\x12\x1c\n" +
	"\tcandidate\x18\x02 \x03(\tR\tcandidate\"\x9e\x03\n" +
	"\x16ParseFileSliceResponse\x12)\n" +
	"\x10content_identity\x18\x01 \x01(\tR\x0fcontentIdentity\x12\x1d\n" +
	"\n" +
	"meta_nodes\x18\x02 \x03(\tR\tmetaNodes\x12\x1b\n" +
	"\traw_nodes\x18\x03 \x03(\tR\brawNodes\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x120\n" +
	"\x05sizes\x18\x05 \x03(\v2\x1a.v6.services.pub.SliceSizeR\x05sizes\x12\x12\n" +
	"\x04sha1\x18\x06 \x01(\tR\x04sha1\x12\x19\n" +
	"\bwcs_etag\x18\a \x01(\tR\awcsEtag\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"store_type\x18\n" +
	" \x01(\x03R\tstoreType\x12X\n" +
	"\x16raw_download_addresses\x18\v \x03(\v2\".v6.services.pub.SliceDownloadInfoR\x14rawDownloadAddresses\"]\n" +
	"\tSliceSize\x12\x1f\n" +
	"\vstart_index\x18\x01 \x01(\x03R\n" +
	"startIndex\x12\x1b\n" +
	"\tend_index\x18\x02 \x01(\x03R\bendIndex\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x99\x01\n" +
	"\x1bSliceDownloadAddressRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x03(\tR\bidentity\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x12\n" +
	"\x04flag\x18\x04 \x01(\x03R\x04flag\x12\x14\n" +
	"\x05parse\x18\x05 \x01(\bR\x05parse\"\xc0\x01\n" +
	"\x1cSliceDownloadAddressResponse\x12@\n" +
	"\taddresses\x18\x01 \x03(\v2\".v6.services.pub.SliceDownloadInfoR\taddresses\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\x12'\n" +
	"\x0frequest_address\x18\x03 \x01(\tR\x0erequestAddress\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"\xd1\x02\n" +
	"\x1bFileDownloadAddressResponse\x12)\n" +
	"\x10download_address\x18\x01 \x01(\tR\x0fdownloadAddress\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\x12'\n" +
	"\x0frequest_address\x18\x03 \x01(\tR\x0erequestAddress\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x18\n" +
	"\aencrypt\x18\x05 \x01(\x05R\aencrypt\x12\x1d\n" +
	"\n" +
	"store_type\x18\x06 \x01(\x03R\tstoreType\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12)\n" +
	"\x10content_identity\x18\n" +
	" \x01(\tR\x0fcontentIdentity\"\xba\x01\n" +
	"\x11SliceDownloadInfo\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12)\n" +
	"\x10download_address\x18\x02 \x01(\tR\x0fdownloadAddress\x12%\n" +
	"\x0edownload_token\x18\x03 \x01(\tR\rdownloadToken\x12\x18\n" +
	"\aencrypt\x18\x04 \x01(\x05R\aencrypt\x12\x1d\n" +
	"\n" +
	"store_type\x18\x05 \x01(\x03R\tstoreType\"\xfd\x02\n" +
	"\x0eDocFilePreview\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\b \x01(\x03R\x04type\x12\x1f\n" +
	"\vcan_preview\x18\t \x01(\bR\n" +
	"canPreview\x12'\n" +
	"\x0fpreview_address\x18\n" +
	" \x01(\tR\x0epreviewAddress\x12#\n" +
	"\rpreview_token\x18\v \x01(\tR\fpreviewToken\x12\x19\n" +
	"\bcan_edit\x18\f \x01(\bR\acanEdit\x12!\n" +
	"\fedit_address\x18\r \x01(\tR\veditAddress\x12\x1d\n" +
	"\n" +
	"edit_token\x18\x0e \x01(\tR\teditToken\"\xd7\x03\n" +
	"\x16DownloadAndPreviewInfo\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\b \x01(\x03R\x04type\x12\x1f\n" +
	"\vcan_preview\x18\t \x01(\bR\n" +
	"canPreview\x12\x19\n" +
	"\bcan_edit\x18\n" +
	" \x01(\bR\acanEdit\x12!\n" +
	"\fpreview_type\x18\v \x01(\x05R\vpreviewType\x12#\n" +
	"\rdownload_type\x18\f \x01(\x05R\fdownloadType\x12\x12\n" +
	"\x04sha1\x18\r \x01(\tR\x04sha1\x12!\n" +
	"\fcan_download\x18\x0e \x01(\bR\vcanDownload\x126\n" +
	"\x17cannot_download_message\x18\x0f \x01(\tR\x15cannotDownloadMessage\x12)\n" +
	"\x10content_identity\x18\x10 \x01(\tR\x0fcontentIdentity\"\xbf\x01\n" +
	"\vUploadToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"access_key\x18\n" +
	" \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\v \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06bucket\x18\f \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\r \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x0e \x01(\tR\bendpoint\x12\x10\n" +
	"\x03key\x18\x0f \x01(\tR\x03key\"\xcc\x03\n" +
	"\n" +
	"UploadTask\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12%\n" +
	"\x0eupload_address\x18\x02 \x01(\tR\ruploadAddress\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12!\n" +
	"\fupload_token\x18\x04 \x01(\tR\vuploadToken\x12\x1d\n" +
	"\n" +
	"upload_key\x18\x05 \x01(\tR\tuploadKey\x12\x1d\n" +
	"\n" +
	"access_key\x18\n" +
	" \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\v \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06bucket\x18\f \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\r \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x0e \x01(\tR\bendpoint\x12\x10\n" +
	"\x03key\x18\x0f \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"block_size\x18\x10 \x01(\x03R\tblockSize\x12&\n" +
	"\x0fblock_hash_type\x18\x11 \x01(\x03R\rblockHashType\x12#\n" +
	"\rblock_version\x18\x12 \x01(\x05R\fblockVersion\x12\x1f\n" +
	"\vblock_codec\x18\x13 \x01(\x03R\n" +
	"blockCodec\"\xbd\x02\n" +
	"\x15DirectDownloadRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04flag\x18\x04 \x01(\x03R\x04flag\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1b\n" +
	"\tclient_ua\x18\x06 \x01(\tR\bclientUa\x12!\n" +
	"\fvideo_codecs\x18\a \x03(\tR\vvideoCodecs\x12!\n" +
	"\faudio_codecs\x18\b \x03(\tR\vaudioCodecs\x12\x16\n" +
	"\x06expire\x18\t \x01(\x03R\x06expire\x12\x18\n" +
	"\aencrypt\x18\n" +
	" \x01(\x05R\aencrypt\x12\x14\n" +
	"\x05addon\x18\v \x01(\tR\x05addon\"\xa0\x05\n" +
	"\rPreviewStatus\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\x12\x10\n" +
	"\x03num\x18\a \x01(\x05R\x03num\x12\x1b\n" +
	"\treport_ts\x18\b \x01(\x03R\breportTs\x12\x1f\n" +
	"\vvideo_codec\x18\t \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\n" +
	" \x01(\tR\n" +
	"audioCodec\x12\x14\n" +
	"\x05width\x18\v \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\f \x01(\x05R\x06height\x12\x1a\n" +
	"\bduration\x18\r \x01(\x02R\bduration\x12\x12\n" +
	"\x04size\x18\x0e \x01(\x03R\x04size\x12\x14\n" +
	"\x05extra\x18\x0f \x01(\tR\x05extra\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x10 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tclient_id\x18\x11 \x01(\tR\bclientId\x12)\n" +
	"\x10content_identity\x18\x12 \x01(\tR\x0fcontentIdentity\x12\x1d\n" +
	"\n" +
	"extra_code\x18\x13 \x01(\tR\textraCode\x12#\n" +
	"\rextra_message\x18\x14 \x01(\tR\fextraMessage\x12\x12\n" +
	"\x04name\x18\x15 \x01(\tR\x04name\x12#\n" +
	"\rplayback_type\x18\x16 \x01(\x05R\fplaybackType\x12\x1b\n" +
	"\tplay_mode\x18\x17 \x01(\x05R\bplayMode\x12\x1f\n" +
	"\vcurrent_pos\x18\x18 \x01(\x02R\n" +
	"currentPos2\xe6\x1a\n" +
	"\vPubUserFile\x12V\n" +
	"\x06Create\x12\x15.v6.services.pub.File\x1a\x15.v6.services.pub.File\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v6/userfile/create\x12P\n" +
	"\x03Get\x12\x15.v6.services.pub.File\x1a\x15.v6.services.pub.File\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v6/userfile/get\x12h\n" +
	"\x06Rename\x12\x15.v6.services.pub.File\x1a'.v6.services.pub.BatchOperationResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v6/userfile/rename\x12w\n" +
	"\x05Trash\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v6/userfile/trash\x12u\n" +
	"\x04Move\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v6/userfile/move\x12u\n" +
	"\x04Copy\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v6/userfile/copy\x12y\n" +
	"\x06Delete\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v6/userfile/delete\x12\x84\x01\n" +
	"\vDeleteTrash\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v6/userfile/delete_trash\x12{\n" +
	"\aRecover\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v6/userfile/recover\x12\x84\x01\n" +
	"\vBatchRename\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v6/userfile/batch_rename\x12\x8a\x01\n" +
	"\x0eBatchOperation\x12&.v6.services.pub.BatchOperationRequest\x1a'.v6.services.pub.BatchOperationResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v6/userfile/batch_operation\x12i\n" +
	"\x04List\x12 .v6.services.pub.FileListRequest\x1a!.v6.services.pub.FileListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v6/userfile/list\x12t\n" +
	"\tListTrash\x12 .v6.services.pub.FileListRequest\x1a!.v6.services.pub.FileListResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v6/userfile/list_trash\x12k\n" +
	"\x06Search\x12\x1e.v6.services.pub.SearchRequest\x1a!.v6.services.pub.FileListResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v6/userfile/search\x12\x8e\x01\n" +
	"\x14CreateManageRTCOffer\x12!.v6.services.pub.ManageRTCRequest\x1a\".v6.services.pub.ManageRTCResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v6/userfile/create_manage_rtc_offer\x12\xa0\x01\n" +
	"\x16SendClientIceCandidate\x12(.v6.services.pub.SendIceCandidateRequest\x1a).v6.services.pub.SendIceCandidateResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v6/userfile/send_client_ice_candidate\x12\x9c\x01\n" +
	"\x15GetServerIceCandidate\x12'.v6.services.pub.GetIceCandidateRequest\x1a(.v6.services.pub.GetIceCandidateResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v6/userfile/get_server_ice_candidate\x12z\n" +
	"\x0eParseFileSlice\x12\x15.v6.services.pub.File\x1a'.v6.services.pub.ParseFileSliceResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v6/userfile/parse_file_slice\x12\xaa\x01\n" +
	"\x17GetSliceDownloadAddress\x12,.v6.services.pub.SliceDownloadAddressRequest\x1a-.v6.services.pub.SliceDownloadAddressResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/v6/userfile/get_slice_download_address\x12\xa5\x01\n" +
	"\x18GetDirectDownloadAddress\x12&.v6.services.pub.DirectDownloadRequest\x1a,.v6.services.pub.FileDownloadAddressResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v6/userfile/get_direct_download_address\x12\x92\x01\n" +
	"\x19GetDownloadAndPreviewInfo\x12\x15.v6.services.pub.File\x1a'.v6.services.pub.DownloadAndPreviewInfo\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v6/userfile/get_download_and_preview_info\x12i\n" +
	"\n" +
	"PreviewDoc\x12\x15.v6.services.pub.File\x1a\x1f.v6.services.pub.DocFilePreview\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v6/userfile/preview_doc\x12g\n" +
	"\tCreateDoc\x12\x15.v6.services.pub.File\x1a\x1f.v6.services.pub.DocFilePreview\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v6/userfile/create_doc\x12u\n" +
	"\x11CreateUploadToken\x12\x15.v6.services.pub.File\x1a\x1c.v6.services.pub.UploadToken\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v6/userfile/create_upload_token\x12r\n" +
	"\x10CreateUploadTask\x12\x15.v6.services.pub.File\x1a\x1b.v6.services.pub.UploadTask\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v6/userfile/create_upload_task\x12|\n" +
	"\x15CreateTemporaryUpload\x12\x15.v6.services.pub.File\x1a\x1b.v6.services.pub.UploadTask\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v6/userfile/create_temporary_upload\x12\x84\x01\n" +
	"\x13ReportPreviewStatus\x12\x1e.v6.services.pub.PreviewStatus\x1a\x1e.v6.services.pub.PreviewStatus\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v6/userfile/report_preview_statusB7Z5github.com/city404/v6-public-rpc-proto/go/v6/userfileb\x06proto3"

var (
	file_userfile_public_user_file_proto_rawDescOnce sync.Once
	file_userfile_public_user_file_proto_rawDescData []byte
)

func file_userfile_public_user_file_proto_rawDescGZIP() []byte {
	file_userfile_public_user_file_proto_rawDescOnce.Do(func() {
		file_userfile_public_user_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userfile_public_user_file_proto_rawDesc), len(file_userfile_public_user_file_proto_rawDesc)))
	})
	return file_userfile_public_user_file_proto_rawDescData
}

var file_userfile_public_user_file_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_userfile_public_user_file_proto_goTypes = []any{
	(*File)(nil),                         // 0: v6.services.pub.File
	(*FileListRequest)(nil),              // 1: v6.services.pub.FileListRequest
	(*SearchRequest)(nil),                // 2: v6.services.pub.SearchRequest
	(*FileListResponse)(nil),             // 3: v6.services.pub.FileListResponse
	(*BatchOperationRequest)(nil),        // 4: v6.services.pub.BatchOperationRequest
	(*BatchOperationResponse)(nil),       // 5: v6.services.pub.BatchOperationResponse
	(*ManageRTCRequest)(nil),             // 6: v6.services.pub.ManageRTCRequest
	(*ManageRTCResponse)(nil),            // 7: v6.services.pub.ManageRTCResponse
	(*SendIceCandidateRequest)(nil),      // 8: v6.services.pub.SendIceCandidateRequest
	(*SendIceCandidateResponse)(nil),     // 9: v6.services.pub.SendIceCandidateResponse
	(*GetIceCandidateRequest)(nil),       // 10: v6.services.pub.GetIceCandidateRequest
	(*GetIceCandidateResponse)(nil),      // 11: v6.services.pub.GetIceCandidateResponse
	(*ParseFileSliceResponse)(nil),       // 12: v6.services.pub.ParseFileSliceResponse
	(*SliceSize)(nil),                    // 13: v6.services.pub.SliceSize
	(*SliceDownloadAddressRequest)(nil),  // 14: v6.services.pub.SliceDownloadAddressRequest
	(*SliceDownloadAddressResponse)(nil), // 15: v6.services.pub.SliceDownloadAddressResponse
	(*FileDownloadAddressResponse)(nil),  // 16: v6.services.pub.FileDownloadAddressResponse
	(*SliceDownloadInfo)(nil),            // 17: v6.services.pub.SliceDownloadInfo
	(*DocFilePreview)(nil),               // 18: v6.services.pub.DocFilePreview
	(*DownloadAndPreviewInfo)(nil),       // 19: v6.services.pub.DownloadAndPreviewInfo
	(*UploadToken)(nil),                  // 20: v6.services.pub.UploadToken
	(*UploadTask)(nil),                   // 21: v6.services.pub.UploadTask
	(*DirectDownloadRequest)(nil),        // 22: v6.services.pub.DirectDownloadRequest
	(*PreviewStatus)(nil),                // 23: v6.services.pub.PreviewStatus
	(*common.ScanListRequest)(nil),       // 24: v6.services.pub.common.ScanListRequest
}
var file_userfile_public_user_file_proto_depIdxs = []int32{
	0,  // 0: v6.services.pub.FileListRequest.parent:type_name -> v6.services.pub.File
	0,  // 1: v6.services.pub.FileListRequest.filter:type_name -> v6.services.pub.File
	24, // 2: v6.services.pub.FileListRequest.list_info:type_name -> v6.services.pub.common.ScanListRequest
	24, // 3: v6.services.pub.SearchRequest.list_info:type_name -> v6.services.pub.common.ScanListRequest
	0,  // 4: v6.services.pub.FileListResponse.files:type_name -> v6.services.pub.File
	24, // 5: v6.services.pub.FileListResponse.list_info:type_name -> v6.services.pub.common.ScanListRequest
	0,  // 6: v6.services.pub.BatchOperationRequest.source:type_name -> v6.services.pub.File
	0,  // 7: v6.services.pub.BatchOperationRequest.dest:type_name -> v6.services.pub.File
	13, // 8: v6.services.pub.ParseFileSliceResponse.sizes:type_name -> v6.services.pub.SliceSize
	17, // 9: v6.services.pub.ParseFileSliceResponse.raw_download_addresses:type_name -> v6.services.pub.SliceDownloadInfo
	17, // 10: v6.services.pub.SliceDownloadAddressResponse.addresses:type_name -> v6.services.pub.SliceDownloadInfo
	0,  // 11: v6.services.pub.PubUserFile.Create:input_type -> v6.services.pub.File
	0,  // 12: v6.services.pub.PubUserFile.Get:input_type -> v6.services.pub.File
	0,  // 13: v6.services.pub.PubUserFile.Rename:input_type -> v6.services.pub.File
	4,  // 14: v6.services.pub.PubUserFile.Trash:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 15: v6.services.pub.PubUserFile.Move:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 16: v6.services.pub.PubUserFile.Copy:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 17: v6.services.pub.PubUserFile.Delete:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 18: v6.services.pub.PubUserFile.DeleteTrash:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 19: v6.services.pub.PubUserFile.Recover:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 20: v6.services.pub.PubUserFile.BatchRename:input_type -> v6.services.pub.BatchOperationRequest
	4,  // 21: v6.services.pub.PubUserFile.BatchOperation:input_type -> v6.services.pub.BatchOperationRequest
	1,  // 22: v6.services.pub.PubUserFile.List:input_type -> v6.services.pub.FileListRequest
	1,  // 23: v6.services.pub.PubUserFile.ListTrash:input_type -> v6.services.pub.FileListRequest
	2,  // 24: v6.services.pub.PubUserFile.Search:input_type -> v6.services.pub.SearchRequest
	6,  // 25: v6.services.pub.PubUserFile.CreateManageRTCOffer:input_type -> v6.services.pub.ManageRTCRequest
	8,  // 26: v6.services.pub.PubUserFile.SendClientIceCandidate:input_type -> v6.services.pub.SendIceCandidateRequest
	10, // 27: v6.services.pub.PubUserFile.GetServerIceCandidate:input_type -> v6.services.pub.GetIceCandidateRequest
	0,  // 28: v6.services.pub.PubUserFile.ParseFileSlice:input_type -> v6.services.pub.File
	14, // 29: v6.services.pub.PubUserFile.GetSliceDownloadAddress:input_type -> v6.services.pub.SliceDownloadAddressRequest
	22, // 30: v6.services.pub.PubUserFile.GetDirectDownloadAddress:input_type -> v6.services.pub.DirectDownloadRequest
	0,  // 31: v6.services.pub.PubUserFile.GetDownloadAndPreviewInfo:input_type -> v6.services.pub.File
	0,  // 32: v6.services.pub.PubUserFile.PreviewDoc:input_type -> v6.services.pub.File
	0,  // 33: v6.services.pub.PubUserFile.CreateDoc:input_type -> v6.services.pub.File
	0,  // 34: v6.services.pub.PubUserFile.CreateUploadToken:input_type -> v6.services.pub.File
	0,  // 35: v6.services.pub.PubUserFile.CreateUploadTask:input_type -> v6.services.pub.File
	0,  // 36: v6.services.pub.PubUserFile.CreateTemporaryUpload:input_type -> v6.services.pub.File
	23, // 37: v6.services.pub.PubUserFile.ReportPreviewStatus:input_type -> v6.services.pub.PreviewStatus
	0,  // 38: v6.services.pub.PubUserFile.Create:output_type -> v6.services.pub.File
	0,  // 39: v6.services.pub.PubUserFile.Get:output_type -> v6.services.pub.File
	5,  // 40: v6.services.pub.PubUserFile.Rename:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 41: v6.services.pub.PubUserFile.Trash:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 42: v6.services.pub.PubUserFile.Move:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 43: v6.services.pub.PubUserFile.Copy:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 44: v6.services.pub.PubUserFile.Delete:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 45: v6.services.pub.PubUserFile.DeleteTrash:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 46: v6.services.pub.PubUserFile.Recover:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 47: v6.services.pub.PubUserFile.BatchRename:output_type -> v6.services.pub.BatchOperationResponse
	5,  // 48: v6.services.pub.PubUserFile.BatchOperation:output_type -> v6.services.pub.BatchOperationResponse
	3,  // 49: v6.services.pub.PubUserFile.List:output_type -> v6.services.pub.FileListResponse
	3,  // 50: v6.services.pub.PubUserFile.ListTrash:output_type -> v6.services.pub.FileListResponse
	3,  // 51: v6.services.pub.PubUserFile.Search:output_type -> v6.services.pub.FileListResponse
	7,  // 52: v6.services.pub.PubUserFile.CreateManageRTCOffer:output_type -> v6.services.pub.ManageRTCResponse
	9,  // 53: v6.services.pub.PubUserFile.SendClientIceCandidate:output_type -> v6.services.pub.SendIceCandidateResponse
	11, // 54: v6.services.pub.PubUserFile.GetServerIceCandidate:output_type -> v6.services.pub.GetIceCandidateResponse
	12, // 55: v6.services.pub.PubUserFile.ParseFileSlice:output_type -> v6.services.pub.ParseFileSliceResponse
	15, // 56: v6.services.pub.PubUserFile.GetSliceDownloadAddress:output_type -> v6.services.pub.SliceDownloadAddressResponse
	16, // 57: v6.services.pub.PubUserFile.GetDirectDownloadAddress:output_type -> v6.services.pub.FileDownloadAddressResponse
	19, // 58: v6.services.pub.PubUserFile.GetDownloadAndPreviewInfo:output_type -> v6.services.pub.DownloadAndPreviewInfo
	18, // 59: v6.services.pub.PubUserFile.PreviewDoc:output_type -> v6.services.pub.DocFilePreview
	18, // 60: v6.services.pub.PubUserFile.CreateDoc:output_type -> v6.services.pub.DocFilePreview
	20, // 61: v6.services.pub.PubUserFile.CreateUploadToken:output_type -> v6.services.pub.UploadToken
	21, // 62: v6.services.pub.PubUserFile.CreateUploadTask:output_type -> v6.services.pub.UploadTask
	21, // 63: v6.services.pub.PubUserFile.CreateTemporaryUpload:output_type -> v6.services.pub.UploadTask
	23, // 64: v6.services.pub.PubUserFile.ReportPreviewStatus:output_type -> v6.services.pub.PreviewStatus
	38, // [38:65] is the sub-list for method output_type
	11, // [11:38] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_userfile_public_user_file_proto_init() }
func file_userfile_public_user_file_proto_init() {
	if File_userfile_public_user_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userfile_public_user_file_proto_rawDesc), len(file_userfile_public_user_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userfile_public_user_file_proto_goTypes,
		DependencyIndexes: file_userfile_public_user_file_proto_depIdxs,
		MessageInfos:      file_userfile_public_user_file_proto_msgTypes,
	}.Build()
	File_userfile_public_user_file_proto = out.File
	file_userfile_public_user_file_proto_goTypes = nil
	file_userfile_public_user_file_proto_depIdxs = nil
}
