// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: offline/public_user_offline.proto

package offline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PubOfflineTask_Parse_FullMethodName = "/v6.services.pub.PubOfflineTask/Parse"
)

// PubOfflineTaskClient is the client API for PubOfflineTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PubOfflineTaskClient interface {
	Parse(ctx context.Context, in *TaskParseRequest, opts ...grpc.CallOption) (*TaskParseResponse, error)
}

type pubOfflineTaskClient struct {
	cc grpc.ClientConnInterface
}

func NewPubOfflineTaskClient(cc grpc.ClientConnInterface) PubOfflineTaskClient {
	return &pubOfflineTaskClient{cc}
}

func (c *pubOfflineTaskClient) Parse(ctx context.Context, in *TaskParseRequest, opts ...grpc.CallOption) (*TaskParseResponse, error) {
	out := new(TaskParseResponse)
	err := c.cc.Invoke(ctx, PubOfflineTask_Parse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubOfflineTaskServer is the server API for PubOfflineTask service.
// All implementations must embed UnimplementedPubOfflineTaskServer
// for forward compatibility
type PubOfflineTaskServer interface {
	Parse(context.Context, *TaskParseRequest) (*TaskParseResponse, error)
	mustEmbedUnimplementedPubOfflineTaskServer()
}

// UnimplementedPubOfflineTaskServer must be embedded to have forward compatible implementations.
type UnimplementedPubOfflineTaskServer struct {
}

func (UnimplementedPubOfflineTaskServer) Parse(context.Context, *TaskParseRequest) (*TaskParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedPubOfflineTaskServer) mustEmbedUnimplementedPubOfflineTaskServer() {}

// UnsafePubOfflineTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubOfflineTaskServer will
// result in compilation errors.
type UnsafePubOfflineTaskServer interface {
	mustEmbedUnimplementedPubOfflineTaskServer()
}

func RegisterPubOfflineTaskServer(s grpc.ServiceRegistrar, srv PubOfflineTaskServer) {
	s.RegisterService(&PubOfflineTask_ServiceDesc, srv)
}

func _PubOfflineTask_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubOfflineTaskServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubOfflineTask_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubOfflineTaskServer).Parse(ctx, req.(*TaskParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PubOfflineTask_ServiceDesc is the grpc.ServiceDesc for PubOfflineTask service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubOfflineTask_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v6.services.pub.PubOfflineTask",
	HandlerType: (*PubOfflineTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _PubOfflineTask_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offline/public_user_offline.proto",
}
